### ISSUE TITLE
Return more less specific certificate when searching for a more specific

### ISSUE THREAD

**Issue by ties** [NLnetLabs/JDR-web#30]
As a user, in some scenarios, it would help me if I could search for more specifics and get the result of the less-specific certificate containing the resource.

This appears to be implemented for ROAs but not for certificates

**Comment by DRiKE** [comment]
Currently, the search results are actually solely based on ROA contents. So if no VRP exists for a given prefix, JDR will not show you the certificate listing that prefix. The changes in the backend to improve this are already there (because we wanted to do #25), but we still need to adapt the front-end to incorporate this in a nice way. The ticket for that is (the somewhat rough) #27, please feel free to throw in any thoughts there as well.

**Comment by DRiKE** [comment]
@ties We've just deployed a new version where the search results include resources found on certificates, and adheres to the behavior you described. I'm closing this issue for now, but feel free to reopen if need be.

**Comment by ties** [comment]
Thanks for implementing this!
